### ISSUE TITLE
Drygmy charm (possibly other items) duplication bug

### ISSUE THREAD

**Issue by Chocorean** [ChosenArchitect/Project-Architect-2#91]
**Describe the bug**
I was able to duplicate a drygmy charm by killing a summoned drygmy with an Apotheosis tool.

**To Reproduce**
Quite unsure. I just kill the mob with my axe, I imagine the bug comes from: "Enemies below 7% health will be executed."
It might trigger twice the death or something, in the mean time I'll edit the issue if I notice the bug with other entities (think dragon, wither, chimera..)
It only drops one charm with my other tools.

**Expected behavior**
Only one charm should drop, no matter the tool used to kill the summoned drygmy.

**Screenshots**
![image](https://github.com/user-attachments/assets/2b864d6f-cc06-4e31-b022-df48136d49a6)

**Modpack version**
3.0
**Modpack Launcher Used**
FTB
**Ram Allocated**
Default

Thanks!

**Comment by ChosenArchitect** [comment]
Should be fixed next update!
![image](https://github.com/user-attachments/assets/37f1b6ab-417d-4430-8041-0adf756320cc)

**Comment by Chocorean** [comment]
After upgrading to 3.1, I can still reproduce the dup! My drygmys are taking over the world..

**Comment by ChosenArchitect** [comment]
Strange and seems like a one-off thing and its not a huge deal
